Dev/feature: ['feature/*', 'feat/*']
Dev/enhance: ['enhance/*', 'enhancement/*']
Dev/bug: ['fix/*', 'bugfix/*', 'bug/*']
Dev/hotfix: ['hotfix/*']
Dev/security: ['security/*']
Dev/refactoring: ['refactoring/*', 'refactor/*']
Dev/stability: ['performance/*', 'test/*', 'testing/*']
Dev/automated: ['renovate/*']
Dev/docs: ['docs/*', 'document/*']
Dev/chore: ['chore/*', 'maintenance/*', 'other/*', 'others/*']
Dev/branding: ['branding/*']
